export const DEFAULT_GROK_PATTERNS: Record<string, string> = {
  USER: '[a-zA-Z0-9._-]+',
  INT: '(?:[+-]?[0-9]+)',
  BASE10NUM: '(?:[+-]?(?:[0-9]+(?:\\.[0-9]+)?|\\.[0-9]+))',
  NUMBER: '(?:%{BASE10NUM})',
  BASE16NUM: '(?:[+-]?(?:0x)?[0-9A-Fa-f]+)',
  BASE16FLOAT: '(?:[+-]?(?:0x)?(?:[0-9A-Fa-f]+(?:\\.[0-9A-Fa-f]*)?|\\.[0-9A-Fa-f]+))',
  POSINT: '(?:[1-9][0-9]*)',
  NONNEGINT: '(?:[0-9]+)',
  WORD: '(?:\\w+)',
  NOTSPACE: '\\S+',
  SPACE: '\\s*',
  DATA: '.*?',
  GREEDYDATA: '.*',
  QUOTEDSTRING: '(?:"(?:[^"\\\\]|\\\\.)*"|\'(?:[^\'\\\\]|\\\\.)*\')',
  UUID: '[A-Fa-f0-9]{8}-(?:[A-Fa-f0-9]{4}-){3}[A-Fa-f0-9]{12}',
  MAC: '(?:%{CISCOMAC}|%{WINDOWSMAC}|%{COMMONMAC})',
  CISCOMAC: '(?:[A-Fa-f0-9]{4}\\.[A-Fa-f0-9]{4}\\.[A-Fa-f0-9]{4})',
  WINDOWSMAC: '(?:[A-Fa-f0-9]{2}-[A-Fa-f0-9]{2}-[A-Fa-f0-9]{2}-[A-Fa-f0-9]{2}-[A-Fa-f0-9]{2}-[A-Fa-f0-9]{2})',
  COMMONMAC: '(?:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2}:[A-Fa-f0-9]{2})',
  IPV6: '(?:(?:[0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(?:[0-9A-Fa-f]{1,4}:){1,7}:|(?:[0-9A-Fa-f]{1,4}:){1,6}:[0-9A-Fa-f]{1,4}|(?:[0-9A-Fa-f]{1,4}:){1,5}(?::[0-9A-Fa-f]{1,4}){1,2}|(?:[0-9A-Fa-f]{1,4}:){1,4}(?::[0-9A-Fa-f]{1,4}){1,3}|(?:[0-9A-Fa-f]{1,4}:){1,3}(?::[0-9A-Fa-f]{1,4}){1,4}|(?:[0-9A-Fa-f]{1,4}:){1,2}(?::[0-9A-Fa-f]{1,4}){1,5}|[0-9A-Fa-f]{1,4}:(?::[0-9A-Fa-f]{1,4}){1,6}|:(?::[0-9A-Fa-f]{1,4}){1,7}|::(?:[Ff]{4}:)?(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|(?:[0-9A-Fa-f]{1,4}:){1,4}:(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))',
  IPV4: '(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])',
  IP: '(?:%{IPV6}|%{IPV4})',
  HOSTNAME: '(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\\.[0-9A-Za-z][0-9A-Za-z-]{0,62})*',
  IPORHOST: '(?:%{IP}|%{HOSTNAME})',
  EMAILLOCALPART: '[a-zA-Z0-9.!#$%&\'*+/=?^_`{|}~-]+',
  EMAILADDRESS: '%{EMAILLOCALPART}@%{HOSTNAME}',
  HTTPDUSER: '(?:[a-zA-Z0-9._-]+|%{UUID})',
  ISO8601_SECOND: '(?:%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?)',
  DATE: '%{DATE_US}|%{DATE_EU}|%{DATE_ISO}',
  DATESTAMP: '%{DATE}[- ]%{TIME}',
  TZ: '(?:Z|[+-]%{HOUR}(?::?%{MINUTE}))',
  ISO8601_TIMEZONE: '(?:Z|[+-]%{HOUR}(?::?%{MINUTE}))',
  TIME: '%{HOUR}:%{MINUTE}(?::?%{SECOND})',
  TIME_US: '%{HOUR}:%{MINUTE}(?::?%{SECOND})(?::?%{INT})?\\s*%{AMPM}',
  DATESTAMP_OTHER: '%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{TZ} %{YEAR}',
  DATESTAMP_RFC822: '%{DAY} %{MONTH} %{MONTHDAY}, %{YEAR} %{TIME} %{TZ}',
  DATESTAMP_ISO8601: '%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?',
  DATE_US: '%{MONTHNUM}[/-]%{MONTHDAY}[/-]%{YEAR}',
  DATE_EU: '%{MONTHDAY}[./-]%{MONTHNUM}[./-]%{YEAR}',
  DATE_ISO: '%{YEAR}[./-]%{MONTHNUM}[./-]%{MONTHDAY}',
  YEAR: '\\d{4}',
  MONTHNUM: '\\d{1,2}',
  MONTHDAY: '\\d{1,2}',
  HOUR: '(?:2[0123]|[01]?[0-9])',
  MINUTE: '(?:[0-5][0-9])',
  SECOND: '(?:[0-5][0-9]|60)(?:[.,][0-9]+)?',
  AMPM: '(?:[APap][Mm])',
  MONTH: '(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)',
  DAY: '(?:Mon(?:day)?|Tue(?:sday)?|Wed(?:nesday)?|Thu(?:rsday)?|Fri(?:day)?|Sat(?:urday)?|Sun(?:day)?)',
  UNIXPATH: '(?:/[\\w@%+=:,./-]*)+',
  WINPATH: '[A-Za-z]*:?\\\\(?:[^\\\\/:*?"<>|\\r\\n]+\\\\)*[^\\\\/:*?"<>|\\r\\n]*',
  URIPROTO: '[A-Za-z]+(?:\\+[A-Za-z]+)?',
  URIHOST: '(?:%{IPORHOST})(?::%{POSINT})?',
  URIPATH: '(?:/[^\\s?]+)',
  URIPARAM: '(?:\\?\\S*)',
  URIPATHPARAM: '(?:%{URIPATH}(?:%{URIPARAM})?)',
  URI: '%{URIPROTO}://(?:%{USER}(?::[^@]*)?@)?(?:%{URIHOST})?(?:%{URIPATHPARAM})?',
  SYSLOGTIMESTAMP: '%{MONTH} +%{MONTHDAY} %{TIME}',
  SYSLOGPROG: '%{PROG}(?:\\[%{POSINT}\\])?',
  PROG: '[\\x21-\\x5a\\x5e-\\x7e]+',
  HTTPD20: '%{IP:clientip} %{USER:ident} %{USER:auth} \\[%{HTTPDATE:timestamp}\\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)',
  COMBINEDAPACHELOG: '%{IP:clientip} %{USER:ident} %{USER:auth} \\[%{HTTPDATE:timestamp}\\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER}|-) "%{NOTSPACE:referrer}" "%{GREEDYDATA:agent}"',
  NGINXACCESS: '%{IP:client_ip} - (?:%{USER:remote_user}|-) \\[%{HTTPDATE:timestamp}\\] "%{WORD:method} %{NOTSPACE:path}(?: HTTP/%{NUMBER:http_version})?" %{NUMBER:status} %{NUMBER:body_bytes_sent}(?: "%{NOTSPACE:http_referer}" "%{DATA:http_user_agent}"(?: %{NUMBER:response_time})?)?',
  SYSLOG5424PRI: '<%{NONNEGINT:syslog5424_pri}>',
  SYSLOG5424LINE: '%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} +(?:%{TIMESTAMP_ISO8601:syslog5424_ts}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(?:%{NOTSPACE:syslog5424_app}|-) +(?:%{NOTSPACE:syslog5424_proc}|-) +(?:%{NOTSPACE:syslog5424_msgid}|-) +(?:%{SYSLOG5424SD:syslog5424_sd}|-|) +%{GREEDYDATA:syslog5424_msg}',
  SYSLOG5424SD: '\\[+%{GREEDYDATA}\\]+',
  HTTPDATE_DAY: '(?:0[1-9]|[12][0-9]|3[01])',
  HTTPDATE_MON: '(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)',
  HTTPDATE_YEAR: '(?:19|20|21)\\d\\d',
  HTTPDATE_TIME: '(?:(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9])(?::?(?:(?:[0-5][0-9]|60)(?:[.,][0-9]+)?)))',
  HTTPDATE_TZ: '(?:[+-]?(?:[0-9]+))',
  HTTPDATE: '(?:%{HTTPDATE_DAY}/%{HTTPDATE_MON}/%{HTTPDATE_YEAR}:%{HTTPDATE_TIME} %{HTTPDATE_TZ})',
  TIMESTAMP_ISO8601: '%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?'
};
