import { inferFormat } from '../index';

describe('Format Inferrer', () => {
  it('should reject insufficient sample lines', () => {
    const lines = ['line1', 'line2'];
    const result = inferFormat(lines);
    expect(result.suggestions.length).toBe(0);
  });

  it('should detect JSON format', () => {
    const lines = [];
    for (let i = 0; i < 30; i++) {
      lines.push(JSON.stringify({
        timestamp: '2024-06-10T14:30:00Z',
        level: 'INFO',
        message: `Log entry ${i}`,
        service: 'test-app'
      }));
    }
    const result = inferFormat(lines);
    const jsonSuggestion = result.suggestions.find(s => s.name === 'JSON Log');
    expect(jsonSuggestion).toBeDefined();
    expect(jsonSuggestion!.matchRate).toBeGreaterThan(0.8);
  });

  it('should detect NGINX format', () => {
    const lines = [];
    const paths = ['/api/users', '/api/products', '/api/orders', '/health'];
    const methods = ['GET', 'POST', 'PUT', 'DELETE'];
    const statuses = [200, 201, 404, 500, 301];
    for (let i = 0; i < 30; i++) {
      const ip = `192.168.${Math.floor(i / 10)}.${i % 255}`;
      const method = methods[i % methods.length];
      const path = paths[i % paths.length];
      const status = statuses[i % statuses.length];
      lines.push(`${ip} - - [10/Jun/2024:14:${30 + i % 30}:${String(i % 60).padStart(2, '0')} +0000] "${method} ${path} HTTP/1.1" ${status} ${100 + i * 10}`);
    }
    const result = inferFormat(lines);
    const nginxSuggestion = result.suggestions.find(s => s.name.includes('NGINX'));
    expect(nginxSuggestion).toBeDefined();
    expect(nginxSuggestion!.matchRate).toBeGreaterThan(0.5);
  });

  it('should generate auto pattern when no builtin matches well', () => {
    const lines = [];
    for (let i = 0; i < 30; i++) {
      lines.push(`field1_val_${i}\tfield2_${i * 100}\t2024-06-10 14:30:${String(i % 60).padStart(2, '0')}\tmessage_${i}`);
    }
    const result = inferFormat(lines);
    expect(result.autoGeneratedPattern).toBeDefined();
    expect(result.autoGeneratedMatchRate).toBeGreaterThan(0.5);
  });

  it('should limit suggestions to maxSuggestions', () => {
    const lines = [];
    for (let i = 0; i < 30; i++) {
      lines.push(JSON.stringify({ msg: `log ${i}` }));
    }
    const result = inferFormat(lines, 2);
    expect(result.suggestions.length).toBeLessThanOrEqual(2);
  });
});
