import { compileGrokPattern, testGrokMatchRate, CompiledGrok, matchGrok } from '../grok/engine';
import { DEFAULT_GROK_PATTERNS } from '../grok/patterns';
import { GrokMatch } from '../grok/engine';

export interface FormatSuggestion {
  name: string;
  pattern: string;
  matchRate: number;
  matchedCount: number;
  totalCount: number;
  sampleMatches: Array<{ line: string; match: GrokMatch }>;
}

export interface InferredFormat {
  suggestions: FormatSuggestion[];
  autoGeneratedPattern?: string;
  autoGeneratedMatchRate?: number;
  separator?: string;
  fieldNames?: string[];
}

const BUILTIN_PATTERNS: Array<{ name: string; pattern: string }> = [
  { name: 'NGINX Access Log', pattern: DEFAULT_GROK_PATTERNS.NGINXACCESS },
  { name: 'Apache Combined Log', pattern: DEFAULT_GROK_PATTERNS.COMBINEDAPACHELOG },
  { name: 'Apache Common Log', pattern: DEFAULT_GROK_PATTERNS.HTTPD20 },
  { name: 'Syslog RFC5424', pattern: DEFAULT_GROK_PATTERNS.SYSLOG5424LINE },
  { name: 'Syslog Legacy', pattern: `%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{SYSLOGPROG:program}: %{GREEDYDATA:message}` },
  { name: 'JSON Log', pattern: '\\{.*\\}' }
];

const SEPARATORS = [
  { name: 'space', char: ' ', regex: /\s+/, grok: '%{NOTSPACE}' },
  { name: 'tab', char: '\t', regex: /\t/, grok: '%{NOTSPACE}' },
  { name: 'pipe', char: '|', regex: /\|/, grok: '%{DATA}' },
  { name: 'comma', char: ',', regex: /,/, grok: '%{DATA}' },
  { name: 'semicolon', char: ';', regex: /;/, grok: '%{DATA}' }
];

export function inferFormat(sampleLines: string[], maxSuggestions: number = 5): InferredFormat {
  const cleanedLines = sampleLines.map(l => l.trim()).filter(l => l.length > 0);
  if (cleanedLines.length < 10) {
    return {
      suggestions: [],
      autoGeneratedPattern: undefined,
      autoGeneratedMatchRate: undefined
    };
  }

  const testLines = cleanedLines.slice(0, Math.min(100, cleanedLines.length));

  const suggestions: FormatSuggestion[] = [];

  for (const builtin of BUILTIN_PATTERNS) {
    try {
      if (builtin.name === 'JSON Log') {
        const jsonMatches = testLines.filter(l => {
          try { JSON.parse(l); return true; } catch { return false; }
        }).length;
        const rate = jsonMatches / testLines.length;
        if (rate > 0.8) {
          suggestions.push({
            name: builtin.name,
            pattern: 'JSON',
            matchRate: rate,
            matchedCount: jsonMatches,
            totalCount: testLines.length,
            sampleMatches: testLines.slice(0, 3).map(line => ({
              line,
              match: (() => { try { return JSON.parse(line); } catch { return {}; } })()
            }))
          });
        }
      } else {
        const compiled = compileGrokPattern(builtin.pattern);
        const result = testGrokMatchRate(compiled, testLines);
        if (result.rate > 0.5) {
          suggestions.push({
            name: builtin.name,
            pattern: builtin.pattern,
            matchRate: result.rate,
            matchedCount: result.matched,
            totalCount: result.total,
            sampleMatches: result.sampleMatches
          });
        }
      }
    } catch {
      continue;
    }
  }

  suggestions.sort((a, b) => b.matchRate - a.matchRate);

  const topSuggestion = suggestions[0];
  let autoGeneratedPattern: string | undefined;
  let autoGeneratedMatchRate: number | undefined;

  if (!topSuggestion || topSuggestion.matchRate < 0.8) {
    const autoResult = tryAutoInferPattern(testLines);
    if (autoResult) {
      autoGeneratedPattern = autoResult.pattern;
      autoGeneratedMatchRate = autoResult.matchRate;
    }
  }

  return {
    suggestions: suggestions.slice(0, maxSuggestions),
    autoGeneratedPattern,
    autoGeneratedMatchRate
  };
}

interface AutoInferResult {
  pattern: string;
  matchRate: number;
  separator?: string;
  fieldNames?: string[];
}

function tryAutoInferPattern(lines: string[]): AutoInferResult | null {
  let bestResult: AutoInferResult | null = null;

  for (const sep of SEPARATORS) {
    const result = trySeparatorPattern(lines, sep);
    if (result && (!bestResult || result.matchRate > bestResult.matchRate)) {
      bestResult = result;
    }
  }

  const keyValueResult = tryKeyValuePattern(lines);
  if (keyValueResult && (!bestResult || keyValueResult.matchRate > bestResult.matchRate)) {
    bestResult = keyValueResult;
  }

  const genericResult = tryGenericPattern(lines);
  if (genericResult && (!bestResult || genericResult.matchRate > bestResult.matchRate)) {
    bestResult = genericResult;
  }

  return bestResult;
}

function trySeparatorPattern(lines: string[], sep: typeof SEPARATORS[0]): AutoInferResult | null {
  const counts: Map<number, number> = new Map();
  for (const line of lines) {
    const parts = line.split(sep.regex);
    counts.set(parts.length, (counts.get(parts.length) || 0) + 1);
  }

  let mostCommonCount = 0;
  let maxCount = 0;
  for (const [numParts, cnt] of counts.entries()) {
    if (cnt > maxCount && numParts >= 3) {
      maxCount = cnt;
      mostCommonCount = numParts;
    }
  }

  if (mostCommonCount < 3 || maxCount / lines.length < 0.7) {
    return null;
  }

  const sampleLines = lines.filter(l => l.split(sep.regex).length === mostCommonCount).slice(0, 10);
  if (sampleLines.length === 0) return null;

  const fieldNames = inferFieldNamesFromSamples(sampleLines, sep.regex, mostCommonCount);
  const grokParts = fieldNames.map((name, i) => {
    return `%{${guessFieldPattern(i, sampleLines, sep.regex)}:${name}}`;
  });

  const pattern = grokParts.join(sep.char === ' ' ? ' ' : `\\${sep.char}`);

  try {
    const compiled = compileGrokPattern(pattern);
    let matched = 0;
    for (const line of lines) {
      if (matchGrok(line, compiled)) matched++;
    }
    const matchRate = matched / lines.length;

    if (matchRate > 0.5) {
      return { pattern, matchRate, separator: sep.name, fieldNames };
    }
  } catch {
    return null;
  }

  return null;
}

function inferFieldNamesFromSamples(lines: string[], splitRe: RegExp, numFields: number): string[] {
  const parts = lines[0].split(splitRe);
  const names: string[] = [];

  for (let i = 0; i < numFields; i++) {
    const sample = parts[i] || '';
    let name = guessFieldName(sample, i);
    while (names.includes(name)) {
      name = `${name}_${i}`;
    }
    names.push(name);
  }

  return names;
}

function guessFieldName(sample: string, index: number): string {
  if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(sample)) return 'client_ip';
  if (/^\d{4}-\d{2}-\d{2}[T ]\d{2}/.test(sample)) return 'timestamp';
  if (/^\d{1,2}\/\w{3}\/\d{4}/.test(sample)) return 'timestamp';
  if (/^[A-Z]{3}\s+\d{1,2}\s+\d{2}/.test(sample)) return 'timestamp';
  if (/^\d{3}$/.test(sample) && parseInt(sample) >= 100 && parseInt(sample) <= 599) return 'status';
  if (/^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$/.test(sample)) return 'method';
  if (/^\//.test(sample)) return 'path';
  if (/^https?:\/\//.test(sample)) return 'url';
  if (sample.includes('@') && sample.includes('.')) return 'email';
  if (/^\d+$/.test(sample)) return `number_${index}`;
  if (/^[a-zA-Z0-9_-]+$/.test(sample) && sample.length < 30) return `field_${index}`;
  return `field_${index}`;
}

function guessFieldPattern(index: number, samples: string[], splitRe: RegExp): string {
  const values = samples.map(l => l.split(splitRe)[index] || '').filter(v => v);
  if (values.length === 0) return 'DATA';

  if (values.every(v => /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(v))) return 'IPV4';
  if (values.every(v => /^\d+$/.test(v))) return 'INT';
  if (values.every(v => /^\d+(\.\d+)?$/.test(v))) return 'NUMBER';
  if (values.every(v => /^[A-Z]+$/.test(v))) return 'WORD';
  if (values.every(v => !v.includes(' '))) return 'NOTSPACE';

  const containsSpaces = values.some(v => v.includes(' '));
  return containsSpaces ? 'DATA' : 'NOTSPACE';
}

function tryKeyValuePattern(lines: string[]): AutoInferResult | null {
  const kvPatterns = [
    /(\w+)=(?:"([^"]*)"|'([^']*)'|(\S+))/g,
    /(\w+)\s*:\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g
  ];

  for (const pattern of kvPatterns) {
    let matched = 0;
    for (const line of lines) {
      const matches = [...line.matchAll(pattern)];
      if (matches.length >= 3) matched++;
    }
    const rate = matched / lines.length;
    if (rate > 0.7) {
      return {
        pattern: '%{GREEDYDATA:raw_message}',
        matchRate: rate
      };
    }
  }

  return null;
}

function tryGenericPattern(lines: string[]): AutoInferResult | null {
  const patterns: Array<{ name: string; compiled: CompiledGrok }> = [];

  const candidates = [
    '%{IPORHOST:host} - %{USER:user} \\[%{HTTPDATE:timestamp}\\] "%{WORD:method} %{URIPATHPARAM:path} HTTP/%{NUMBER:version}" %{INT:status} %{INT:bytes}',
    '%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:host} %{PROG:program}\\[%{POSINT:pid}\\]: %{GREEDYDATA:message}',
    '%{TIMESTAMP_ISO8601:timestamp} %{WORD:level} %{GREEDYDATA:message}',
    '\\[%{TIMESTAMP_ISO8601:timestamp}\\] \\[%{WORD:level}\\] %{GREEDYDATA:message}'
  ];

  for (const p of candidates) {
    try {
      patterns.push({ name: p, compiled: compileGrokPattern(p) });
    } catch { continue; }
  }

  let best: { pattern: string; rate: number } | null = null;
  for (const p of patterns) {
    const result = testGrokMatchRate(p.compiled, lines);
    if (result.rate > 0.4 && (!best || result.rate > best.rate)) {
      best = { pattern: p.name, rate: result.rate };
    }
  }

  if (best) {
    return { pattern: best.pattern, matchRate: best.rate };
  }

  return null;
}

export function saveInferredConfig(format: InferredFormat, outputPath: string, config: any = {}): string {
  const selected = format.suggestions[0];
  let parserConfig: any = {};

  if (selected && selected.matchRate >= 0.8) {
    if (selected.name === 'JSON Log') {
      parserConfig = { format: 'json' };
    } else {
      parserConfig = { format: 'grok', grokPattern: selected.pattern };
    }
  } else if (format.autoGeneratedPattern) {
    parserConfig = { format: 'grok', grokPattern: format.autoGeneratedPattern };
  } else {
    parserConfig = { format: 'grok', grokPattern: '%{GREEDYDATA:message}' };
  }

  const finalConfig = {
    parserConfig,
    suggestions: format.suggestions.map(s => ({
      name: s.name,
      matchRate: `${(s.matchRate * 100).toFixed(1)}%`,
      pattern: s.pattern
    })),
    autoGenerated: format.autoGeneratedPattern ? {
      pattern: format.autoGeneratedPattern,
      matchRate: `${(format.autoGeneratedMatchRate! * 100).toFixed(1)}%`
    } : null,
    ...config
  };

  const yaml = require('js-yaml');
  const content = yaml.dump(finalConfig);
  const fs = require('fs');
  fs.writeFileSync(outputPath, content, 'utf8');
  return content;
}
